language: python
python:
  - 2.6  # RHEL 6
  - 2.7  # RHEL 7
  - 3.5  # Fedora 24+
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm
install:
  - pip install -r requirements.txt -r test-requirements.txt codecov
script:
  - ./configure
  - ./check
after_success:
  - codecov -f coverage.xml
