language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
sudo: required
install:
  - sudo apt-get update
  - sudo apt-get install rpm
  - pip install lxml nose six
script:
  - ./configure
  - ./check
